### main  page
GET http://localhost:3001/

### POST login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email": "james@bond",
    "password": "123456"
}

### POST register
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "email": "vika@vika",
    "password": "123456",
    "userName": "Vika"
}

### GET all users

GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJvbmQiLCJzdWIiOjEsInVzZXJJZCI6MSwidXNlck5hbWUiOiJqYW1lcyIsImlhdCI6MTcwODQxNTc1MiwiZXhwIjoxNzA4NDE5MzUyfQ.BV706VxLvay3a5fef6Lrsghoddp1Grw0Szv3DD4G3Is

### GET all users  who Follows me

GET http://localhost:3001/api//relations/myfollowers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJvbmQiLCJzdWIiOjEsInVzZXJJZCI6MSwidXNlck5hbWUiOiJqYW1lcyIsImlhdCI6MTcwOTAyMzQyMywiZXhwIjoxNzA5MDI3MDIzfQ.9AdRq_AfIki4fBfoUPdvuKTki3rUFeo0b8I97NiTFkY

### GET all users who I follow

GET http://localhost:3001/api/relations/myfollows
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJvbmQiLCJzdWIiOjEsInVzZXJJZCI6MSwidXNlck5hbWUiOiJqYW1lcyIsImlhdCI6MTcwOTAyMzQyMywiZXhwIjoxNzA5MDI3MDIzfQ.9AdRq_AfIki4fBfoUPdvuKTki3rUFeo0b8I97NiTFkY

### POST relation
POST http://localhost:3001/api/relations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJvbmQiLCJzdWIiOjEsInVzZXJJZCI6MSwidXNlck5hbWUiOiJqYW1lcyIsImlhdCI6MTcwOTAyMzQyMywiZXhwIjoxNzA5MDI3MDIzfQ.9AdRq_AfIki4fBfoUPdvuKTki3rUFeo0b8I97NiTFkY


{
    "follows": "6",
    "userName": "vika"
}

### DELETE relation
DELETE  http://localhost:3001/api/relations/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJvbmQiLCJzdWIiOjEsInVzZXJJZCI6MSwidXNlck5hbWUiOiJqYW1lcyIsImlhdCI6MTcwOTAzNTg4MSwiZXhwIjoxNzA5MDM5NDgxfQ.fcp_Foy952aMc5xnGGEvV_tEIwkc0N7assAJYdOTbqU

### POST relation
POST http://localhost:3001/api/myMoviesList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJvbmQiLCJzdWIiOjEsInVzZXJJZCI6MSwidXNlck5hbWUiOiJqYW1lcyIsImlhdCI6MTcwOTA0NDc0MywiZXhwIjoxNzA5MDQ4MzQzfQ.V_45lY2IvvAR0T2xbWaLVYQJ8kr6ijRFQCDli1-7Zfc


{
    "movieId": "justLink",
    "description": "very very interesting",
    "title": "Movie Title",
    "imgUrl": "Urls"
}

### PUT update user
PUT http://localhost:3001/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbWVzQGJvbmQiLCJzdWIiOjEsInVzZXJJZCI6MSwidXNlck5hbWUiOiJqYW1lcyIsImlhdCI6MTcwOTEwNzkyMCwiZXhwIjoxNzA5MTExNTIwfQ.0rPUJGyV9spjrmfLhstEr3C3B5LydFgEBKnpv3mSF8A

{
    "userName": "JamesJames",
    "imgUrl": "urlurl"

}